name: test

on: push

jobs:
 Hello:
  name: first test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
    - name: Hello world
      run: echo "Hello world"

